### ISSUE TITLE
ImportError: cannot import name execute_manager

### ISSUE THREAD

**Issue by TimoRiikonen** [Fiedzia/Fang-of-Mongo#27]
Root cause:
This project is very old and not maintained any more. In other words scrap it and look for something else.

If you still want to use this, you need to use an earlier Django version than 1.4:
execute_manager deprecated in Django 1.4 as part of the project layout refactor and was removed in 1.6 per the deprecation timeline: https://docs.djangoproject.com/en/1.4/internals/deprecation/#id3

To fix this error you should either install a compatible version of Django for the project or update the manage.py to new style which does not use execute_manager: https://docs.djangoproject.com/en/1.4/releases/1.4/#updated-default-project-layout-and-manage-py Most likely if your manage.py is not compatible with 1.6 then neither is the rest of the project. You should find the appropriate Django version for the project.

**Comment by whutjs** [comment]
Hi, TimoRiikonen, Is there any requirements for the version of python?

**Comment by TimoRiikonen** [comment]
Hi, sorry but I don't remember and I don't have this environment any more easily reachable, so I don't have any answer to you.

**Comment by AysadKozanoglu** [comment]
First start failure on a fresh installed Debian 8.8 64bit

 ./manage.py runserver

Traceback (most recent call last):
  File "./manage.py", line 2, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager

my python version 
Python 3.4.2

django version:
django-admin --version
1.7.11

**Comment by AysadKozanoglu** [comment]
also dont work on ubuntu 16.04 fresh installed same like above

<<
Traceback (most recent call last):
File "./manage.py", line 2, in
from django.core.management import execute_manager
ImportError: cannot import name execute_manager
>>

**Comment by TimoRiikonen** [comment]
Hi,
Django version must be 1.3.

**Comment by Sussan787** [comment]
Hi dear
